<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5PQG68E" failures="1" tests="3" name="smoke" time="125.047" errors="0" timestamp="2022-10-29T07:58:43 IST">
  <testcase classname="com.supermarket.tests.LogInTest" name="verify_InvalidLogInAlertMessage" time="6.817">
    <failure type="java.lang.AssertionError" message="This testcase failed expected [Alert!] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: This testcase failed expected [Alert!] but found [×
Alert!
Invalid Username/Password]
at com.supermarket.tests.LogInTest.verify_InvalidLogInAlertMessage(LogInTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_InvalidLogInAlertMessage -->
  <testcase classname="com.supermarket.tests.LogInTest" name="verify_LogIn" time="14.287"/>
  <testcase classname="com.supermarket.tests.DashBoardTest" name="verify_Dashboard" time="9.734"/>
</testsuite> <!-- smoke -->
